### ISSUE TITLE
Add quiet option

### ISSUE THREAD

**Issue by kriansa** [GProst/webpack-clean-obsolete-chunks#17]
Hello @GProst 

Thank you for your work on this plugin!

Would you consider adding a "quiet" option to it? Sometimes the output is too noisy.

**Comment by GProst** [comment]
Hi @kriansa ! Sure, will do this today/tomorrow.

**Comment by GProst** [comment]
Done. Use `new CleanObsoleteChunks({verbose: false})`

**Comment by kriansa** [comment]
Thank you for your quick response!
