### ISSUE TITLE
Test failures in webpack4

### ISSUE THREAD

**Issue by jdelStrother** [GProst/webpack-clean-obsolete-chunks#29]
I've been trying to get the test suite running under webpack 4 (https://github.com/GProst/webpack-clean-obsolete-chunks/tree/webpack4), but keep running into extract-text-plugin's error:

```
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.pitch (/Users/jon/Developer/vendor/webpack-clean-obsolete-chunks/test/integration/env/webpack-4/node_modules/extract-text-webpack-plugin/dist/loader.js:59:11)
```

which I'm not having much luck fixing.  Would be nice to have a working test suite before claiming webpack4 support...

**Comment by GProst** [comment]
Apparently, there are some problems with supporting webpack 4 for `extract-text-webpack-plugin`. I found the comment with similar issue here: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-368320690

I think they are suggesting to use other plugin called `mini-css-extract-plugin` (https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/701#issuecomment-374551300). Please read this issue thread and try to resolve the problem with suggestions posted there. If you have no luck after that, I'll look at it too, ok?

**Comment by jdelStrother** [comment]
I ended up reducing it to a mini-app here: https://github.com/jdelStrother/extract-text-with-children/blob/59d4c10625b42b7621122b5827ea6ea5f1cf2c77/build.js#L38-L51 - the problem occurs when using createChildCompiler, where we have the extract-text loader present in the child, but the plugin isn't applied to it.  mini-css-extract-plugin is also subject to the same problems.

The problem is actually also present in the webpack 2 & 3 tests, but in those environments, `stats.hasErrors()` only considers `stats.compilation.errors`, whereas under webpack4, it also checks `stats.compilation.children[].errors` (where this error is hiding), causing the webpack4 tests to fail.

I'm 95% sure this is the correct fix - https://github.com/GProst/webpack-clean-obsolete-chunks/blob/master/test/integration/helper-functions/handle-errors.js - but would appreciate a second opinion.

**Comment by GProst** [comment]
Yeah, I guess this should fix it

**Comment by jdelStrother** [comment]
OK, done
