### ISSUE TITLE
Compiled styles not being cleaned

### ISSUE THREAD

**Issue by jabney** [GProst/webpack-clean-obsolete-chunks#9]
This is a handy plugin, thanks.

It removes old `js` files just fine, but for some reason `css` files are not cleaned.

I'm using version 0.1.7.

<img width="436" alt="screen shot 2017-04-09 at 9 06 08 pm" src="https://cloud.githubusercontent.com/assets/4623522/24845601/71fbc072-1d68-11e7-94fd-7aa5f68d242c.png">

**Comment by GProst** [comment]
Thank you for reporting, I'll see how we can fix it during the day.

**Comment by GProst** [comment]
Did you create those stylesheet files via `extract-text-webpack-plugin`?

**Comment by jabney** [comment]
Yes. Here's my `webpack.config.js` in case it helps (webpack 2.3.3).

```javascript
let path = require('path');
let webpack = require('webpack')
let ExtractTextPlugin = require('extract-text-webpack-plugin');
let HTMLWebpackPlugin = require('html-webpack-plugin');
let CleanObsoleteChunks = require('webpack-clean-obsolete-chunks');

module.exports = [{
    entry: {
        app: './app/index.js',
        vendor: './app/vendor.js'
    },

    output: {
        filename: '[name].[chunkhash].js',
        path: path.resolve(__dirname, 'dist')
    },

    module: {
        rules: [{
            test: /\.scss$/,
            use: ExtractTextPlugin.extract({
                fallback: 'style-loader',
                use: ['css-loader', 'sass-loader']
            })
        },
        {
            test: /\.js$/,
            exclude: /node_modules/,
            use: [{
                loader: 'babel-loader',
                options: {
                    presets: ['babel-preset-es2015'],
                }
            }]
        },
        {
            test: /\.component\.html$/,
            use: ['raw-loader']
        }]
    },
    plugins: [
        new CleanObsoleteChunks(),

        new webpack.optimize.CommonsChunkPlugin({
            name: 'vendor'
        }),

        // new webpack.optimize.UglifyJsPlugin({
        //     compress: {
        //         warnings: false,
        //         drop_console: false
        //     }
        // }),

        new ExtractTextPlugin('styles.[contentHash].css'),

        new HTMLWebpackPlugin({
            template: './app/index.html',
            filename: 'index.html'
        })
    ]
}];
```

**Comment by jabney** [comment]
Here's a project gzip file.
1) Unzip
2) `npm install`
3) `npm run watch`
4) Change some styles: `styles.scss` and `app/components/widget/widget.component.scss`
5) Check output in `/dist`.

[webpack-demo.zip](https://github.com/GProst/webpack-clean-obsolete-chunks/files/909122/webpack-demo.zip)

**Comment by GProst** [comment]
Thank you for your help, I have reproduced and found the issue. The problem is that chunk hash doesn't change if you change a stylesheet file. I'll fix it today but a little bit later.

**Comment by jabney** [comment]
> The problem is that chunk hash doesn't change if you change a stylesheet file.

This must be because `ExtractTextPlugin` is removing the styles from the app chunk, so in the end the styles aren't calculated as part of the chunk hash.

**Comment by jabney** [comment]
I can confirm version 0.1.8 fixes the issue I was having. Obsolete css chucks are now removed.

**Comment by GProst** [comment]
It's great to hear that!
